/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 C:\Users\cgilb\Documents\Code\lotr-quiz\public\models\ring\scene.gltf --transform -jM 
Files: C:\Users\cgilb\Documents\Code\lotr-quiz\public\models\ring\scene.gltf [4.84KB] > scene-transformed.glb [113.18KB] (-2238%)
Author: yaloken (https://sketchfab.com/Yaloken)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/one-ring-b2837bd390424911ab7f7a5fa00b8ad5
Title: One Ring
*/

import { useGLTF } from "@react-three/drei";
import { useRef } from "react";
import { useFrame } from "@react-three/fiber";

export function Ring(props) {
  const ring = useRef();
  const { nodes, materials } = useGLTF("./models/ring/scene-transformed.glb");

  useFrame((state, delta) => {
    ring.current.rotation.y += delta * 0.1;
    ring.current.rotation.x += delta * 0.1;
  });

  // materials.Default.envMapIntensity = 0.01;
  materials.Default.emissiveIntensity = 1;

  return (
    <group ref={ring} {...props} dispose={null} scale={2}>
      <mesh
        geometry={nodes.defaultMaterial.geometry}
        material={materials.Default}
        material-color="#808080"
      ></mesh>
    </group>
  );
}

useGLTF.preload("./models/ring/scene-transformed.glb");
