/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 C:\Users\cgilb\Documents\Code\lotr-quiz\public\models\ring\scene.gltf --transform -jM 
Files: C:\Users\cgilb\Documents\Code\lotr-quiz\public\models\ring\scene.gltf [4.84KB] > scene-transformed.glb [113.18KB] (-2238%)
Author: yaloken (https://sketchfab.com/Yaloken)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/one-ring-b2837bd390424911ab7f7a5fa00b8ad5
Title: One Ring
*/

import { useGLTF } from "@react-three/drei";
import { useRef } from "react";
import { useFrame } from "@react-three/fiber";

import { Bloom, EffectComposer } from "@react-three/postprocessing";

export function Ring(props) {
  const ring = useRef();
  const { nodes, materials } = useGLTF("./models/ring/scene-transformed.glb");

  useFrame((state, delta) => {
    ring.current.rotation.y += delta * 0.1;
    ring.current.rotation.x += delta * 0.1;
  });

  materials.Default.envMapIntensity = 0.2;
  materials.Default.emissiveIntensity = 1;
  materials.Default.toneMapped = false;
  return (
    <group ref={ring} {...props} dispose={null} scale={2}>
      <EffectComposer>
        <Bloom mipmapBlur intensity={0.1}></Bloom>
      </EffectComposer>
      <mesh
        geometry={nodes.defaultMaterial.geometry}
        material={materials.Default}
        envMapIntensity={0.3}
        emissive="orange"
        emissiveIntensity={1}
        toneMapped={false}
      ></mesh>
    </group>
  );
}

useGLTF.preload("./models/ring/scene-transformed.glb");

// material={materials.Default}
// envMapIntensity={0.000001}
